export default [
  {
    id: 1,
    name: "Laptop",
    picture: "/images/Laptop.jpg",
    title: "Best Laptop",
    desc: "Best Laptop with good price. It's the best that you can get. It have superior quality.",
    price: "RS 90000",
    quantity: 1,
    No: 1,
  },
  {
    id: 2,
    name: "first image",
    picture: "/images/2.jpg",
    title: "Headphones",
    desc: "Nice pair of headphones. They can be wore any where. They have ultra best sound quality.",
    price: "RS 4000",
    quantity: 1,
    No: 1,
  },
  {
    id: 3,
    name: "first image",
    title: "Plastic Container",
    picture: "/images/Laundary bag.png",
    desc: "Laundary bag that you can carry for carrying goods. They have best quality.",
    price: "RS 1000",
    quantity: 1,
    No: 1,
  },
  {
    id: 4,
    name: "first image",
    title: "Best Laundary Basket.",
    desc: "Laundary bag that you can carry for carrying goods. They have best quality.",
    picture: "/images/Laundary Basket.png",
    price: "RS 15000",
    quantity: 1,
    No: 1,
  },
  {
    id: 5,
    name: "Watch",
    title: "Watch for women",
    picture: "/images/watch.jpg",
    desc: "Solid black watch for women. It's a smart watch and is digital.",
    price: "RS 10000",
    quantity: 1,
    No: 1,
  },
];
